# api.py
# ═════════════════════════════════════════════════════════════════
# Campus Fraud Shield — REST API
#
# Wraps the exact same detection pipeline the Streamlit app uses
# (core/pipeline.py) behind a proper HTTP API, so the detector can be
# called from anything — a mobile app, a browser extension, another
# service, curl, Postman, etc. — not just the Streamlit UI.
#
# Run locally:
#   uvicorn api:app --reload --port 8000
#
# Then either open http://127.0.0.1:8000/docs for interactive Swagger
# docs (auto-generated by FastAPI), or:
#   curl -X POST http://127.0.0.1:8000/scan \
#        -H "Content-Type: application/json" \
#        -d '{"text": "You won a lottery, pay Rs.500 to claim"}'
# ═════════════════════════════════════════════════════════════════

from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from core.pipeline import run_full_pipeline, SIMULATION_MODE, IMPORT_ERRORS

app = FastAPI(
    title="Campus Fraud Shield API",
    description=(
        "Detects phishing, fake internship/scholarship scams, OTP fraud, "
        "and other scams targeting college students, using a 4-engine "
        "pipeline (rules, domain/URL analysis, semantic ML, and history)."
    ),
    version="1.0.0",
)

# Permissive CORS for now (e.g. a browser extension or local frontend
# calling this from a different origin). Tighten allow_origins to your
# actual frontend's domain before deploying this publicly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ────────────────────────────────────────────────────────────────
# Request / response schemas
# ────────────────────────────────────────────────────────────────

class ScanRequest(BaseModel):
    text: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="The message text to analyze (SMS, email, chat, etc.)",
        examples=["Congratulations! You won Rs.25000 scholarship. Pay Rs.500 processing fee to claim."],
    )


class ScanResponse(BaseModel):
    final_score: float
    label: str
    category: str
    category_display: str
    reasons: List[str] = []
    breakdown: Dict[str, Any] = {}
    formula: str = ""
    override_applied: Optional[str] = None
    conflict_detected: bool = False
    conflict_message: str = ""
    entities_found: List[Any] = []
    extractions: Dict[str, Any] = {}
    action: Dict[str, Any] = {}


class HealthResponse(BaseModel):
    status: str
    simulation_mode: bool
    import_errors: List[str] = []


# ────────────────────────────────────────────────────────────────
# Routes
# ────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse)
def health():
    """
    Reports whether the real detection engines loaded successfully.
    If simulation_mode is true, /scan still works but is using the
    hardcoded fallback logic, not the real 4-engine pipeline — check
    import_errors to see why.
    """
    return {
        "status": "ok",
        "simulation_mode": SIMULATION_MODE,
        "import_errors": IMPORT_ERRORS if SIMULATION_MODE else [],
    }


@app.post("/scan", response_model=ScanResponse)
def scan(req: ScanRequest):
    """
    Analyze a message and return a fraud-risk verdict with explanation.
    Runs the same 4-engine pipeline (rules, domain, semantic ML,
    history) as the Streamlit app.
    """
    text = req.text.strip()
    if not text:
        raise HTTPException(status_code=400, detail="text cannot be empty")

    result = run_full_pipeline(text)
    return result


@app.get("/")
def root():
    return {
        "service": "Campus Fraud Shield API",
        "docs": "/docs",
        "health": "/health",
        "scan_endpoint": "POST /scan",
    }