# api.py
# ═════════════════════════════════════════════════════════════════
# Campus Fraud Shield — REST API
#
# Wraps the exact same detection pipeline the Streamlit app uses
# (core/pipeline.py) behind a proper HTTP API, so the detector can be
# called from anything — a mobile app, a browser extension, another
# service, curl, Postman, etc. — not just the Streamlit UI.
#
# Run locally:
#   python -m uvicorn api:app --reload --port 8000
#
# Then either open http://127.0.0.1:8000/docs for interactive Swagger
# docs (auto-generated by FastAPI), or:
#   curl -X POST http://127.0.0.1:8000/api/v1/scan \
#        -H "Content-Type: application/json" \
#        -d '{"text": "You won a lottery, pay Rs.500 to claim"}'
# ═════════════════════════════════════════════════════════════════

import logging
import time
from typing import Any, Dict, List, Optional

from fastapi import Depends, FastAPI, HTTPException, APIRouter
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from core.pipeline import (
    run_full_pipeline,
    load_scorer,
    load_ml_model,
    load_history,
    get_cache_stats,
    SIMULATION_MODE,
    IMPORT_ERRORS,
)

# ── Logging ─────────────────────────────────────────────────────────
# This IS an entrypoint (unlike core/pipeline.py), so it's the right
# place to configure handlers/format once for the whole process.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

app = FastAPI(
    title="Campus Fraud Shield API",
    description=(
        "Detects phishing, fake internship/scholarship scams, OTP fraud, "
        "and other scams targeting college students, using a 4-engine "
        "pipeline (rules, domain/URL analysis, semantic ML, and history)."
    ),
    version="1.0.0",
)

# Permissive CORS for now (e.g. a browser extension or local frontend
# calling this from a different origin). Tighten allow_origins to your
# actual frontend's domain before deploying this publicly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ────────────────────────────────────────────────────────────────
# Lightweight in-process observability
# ────────────────────────────────────────────────────────────────
# Deliberately NOT prometheus_client (a real dependency, a real metrics
# port, real scrape-config) — this is a single-process demo/hackathon
# deployment, not a multi-instance production service behind a load
# balancer where Prometheus would actually make sense. A hand-rolled
# JSON endpoint gives the same practical value (uptime, throughput,
# latency, cache effectiveness) with zero new dependencies, and is
# trivial to swap for real Prometheus later if this ever runs at a
# scale where that's warranted — the counters below would map directly
# onto prometheus_client Counter/Histogram objects.
import threading as _threading

_metrics_lock = _threading.Lock()
_metrics = {
    "start_time": time.time(),
    "requests_total": 0,
    "requests_by_endpoint": {},   # {"POST /api/v1/scan": 42, ...}
    "scan_latency_ms_total": 0.0,  # sum, for a running average — not
                                    # storing every sample (unbounded
                                    # memory growth on a long-running
                                    # process for no real benefit here)
    "scan_count": 0,
}


@app.middleware("http")
async def _track_request_metrics(request, call_next):
    start = time.perf_counter()
    response = await call_next(request)
    elapsed_ms = (time.perf_counter() - start) * 1000
    endpoint = f"{request.method} {request.url.path}"
    with _metrics_lock:
        _metrics["requests_total"] += 1
        _metrics["requests_by_endpoint"][endpoint] = _metrics["requests_by_endpoint"].get(endpoint, 0) + 1
        if request.url.path == "/api/v1/scan":
            _metrics["scan_latency_ms_total"] += elapsed_ms
            _metrics["scan_count"] += 1
    return response


# ────────────────────────────────────────────────────────────────
# Dependency providers
# ────────────────────────────────────────────────────────────────
# These are what get_scorer/get_ml_clf/get_history *use* by default
# (the same cached singletons app.py uses). The point of routing them
# through Depends() rather than calling load_*() directly inside the
# route is that tests can override just these three functions via
# app.dependency_overrides — e.g. swap in a fake scorer that returns a
# fixed result — without touching core/pipeline.py or monkey-patching
# module internals.
#
# BUG FOUND during audit: previously these called load_*() directly
# with no error handling. If a core dependency (e.g. sentence-
# transformers) failed to import -- SIMULATION_MODE=True -- FastAPI's
# Depends() resolution would raise an unhandled 500 with a raw
# NameError traceback, before run_full_pipeline's own graceful
# simulation-fallback logic ever got a chance to run (that fallback
# only helps once inside the route body, and Depends() resolves
# before the route body executes). Fixed: catch the RuntimeError
# load_*() now raises in that case and return a clean, documented 503
# instead of an opaque crash.

def get_scorer():
    try:
        return load_scorer()
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))


def get_ml_clf():
    try:
        return load_ml_model()
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))


def get_history():
    try:
        return load_history()
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))


# ────────────────────────────────────────────────────────────────
# Request / response schemas
# ────────────────────────────────────────────────────────────────

class ScanRequest(BaseModel):
    text: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="The message text to analyze (SMS, email, chat, etc.)",
        examples=["Congratulations! You won Rs.25000 scholarship. Pay Rs.500 processing fee to claim."],
    )


class ScanResponse(BaseModel):
    final_score: float
    label: str
    category: str
    category_display: str
    reasons: List[str] = []
    breakdown: Dict[str, Any] = {}
    formula: str = ""
    override_applied: Optional[str] = None
    conflict_detected: bool = False
    conflict_message: str = ""
    entities_found: List[Any] = []
    extractions: Dict[str, Any] = {}
    action: Dict[str, Any] = {}


class HealthResponse(BaseModel):
    status: str
    simulation_mode: bool
    import_errors: List[str] = []


class MetricsResponse(BaseModel):
    uptime_seconds: float
    requests_total: int
    requests_by_endpoint: Dict[str, int]
    scan_count: int
    avg_scan_latency_ms: Optional[float] = None
    cache: Dict[str, Any]
    simulation_mode: bool


# ────────────────────────────────────────────────────────────────
# Versioned routes — /api/v1/...
# ────────────────────────────────────────────────────────────────
# Versioning from day one costs nothing right now (nothing depends on
# this API yet) but avoids a breaking rename later once something does.
v1 = APIRouter(prefix="/api/v1")


@v1.get("/health", response_model=HealthResponse)
def health():
    """
    Reports whether the real detection engines loaded successfully.
    If simulation_mode is true, /scan still works but is using the
    hardcoded fallback logic, not the real 4-engine pipeline — check
    import_errors to see why.
    """
    return {
        "status": "ok",
        "simulation_mode": SIMULATION_MODE,
        "import_errors": IMPORT_ERRORS if SIMULATION_MODE else [],
    }


@v1.get("/metrics", response_model=MetricsResponse)
def metrics():
    """
    Basic operational visibility: request volume, average /scan
    latency, and scan-cache effectiveness (hit rate directly shows how
    much duplicate/forwarded-scam traffic the cache in
    core/pipeline.py is absorbing). Not authenticated — if this API is
    ever deployed publicly, put this behind the same auth as any other
    internal endpoint before exposing it.
    """
    with _metrics_lock:
        avg_latency = (
            _metrics["scan_latency_ms_total"] / _metrics["scan_count"]
            if _metrics["scan_count"] > 0 else None
        )
        return {
            "uptime_seconds": round(time.time() - _metrics["start_time"], 1),
            "requests_total": _metrics["requests_total"],
            "requests_by_endpoint": dict(_metrics["requests_by_endpoint"]),
            "scan_count": _metrics["scan_count"],
            "avg_scan_latency_ms": round(avg_latency, 2) if avg_latency is not None else None,
            "cache": get_cache_stats(),
            "simulation_mode": SIMULATION_MODE,
        }


@v1.post("/scan", response_model=ScanResponse)
def scan(
    req: ScanRequest,
    scorer=Depends(get_scorer),
    ml_clf=Depends(get_ml_clf),
    history=Depends(get_history),
):
    """
    Analyze a message and return a fraud-risk verdict with explanation.
    Runs the same 4-engine pipeline (rules, domain, semantic ML,
    history) as the Streamlit app.
    """
    text = req.text.strip()
    if not text:
        raise HTTPException(status_code=400, detail="text cannot be empty")

    result = run_full_pipeline(text, scorer=scorer, ml_clf=ml_clf, history=history)
    return result


app.include_router(v1)


@app.get("/")
def root():
    return {
        "service": "Campus Fraud Shield API",
        "docs": "/docs",
        "health": "/api/v1/health",
        "metrics": "/api/v1/metrics",
        "scan_endpoint": "POST /api/v1/scan",
    }