# fix_csv.py — run this once to fix the dataset
# Place in root folder: python fix_csv.py

import csv
import os

# ── All rows: (text, label, category, source) ────────────────────
ALL_ROWS = [
    # ── ORIGINAL ROWS ─────────────────────────────────────────────
    ("Congratulations! You have been selected for internship at Internshala partner company. Pay Rs.1500 registration fee on Paytm 9876543210 to confirm your slot. Offer expires in 24 hours.", 1, "internship_fee", "dataset"),
    ("Pay Rs.999 joining fee to confirm your work from home internship. Send to PhonePe 8765432109. Limited seats available.", 1, "internship_fee", "dataset"),
    ("You have been selected for data entry internship. Pay Rs.500 security deposit to HRdept@gmail.com. Refundable after 3 months.", 1, "internship_fee", "dataset"),
    ("Internshala internship confirmed! Pay Rs.1200 registration amount to activate your profile. Pay via Paytm 9988776655.", 1, "internship_fee", "dataset"),
    ("Work from home job available. Earn Rs.15000/month. Pay Rs.799 activation fee to get started. Contact 9876501234.", 1, "internship_fee", "dataset"),
    ("Selected for software intern role. Pay Rs.2000 documentation fee to HR@gmail.com within 24 hours to confirm joining.", 1, "internship_fee", "dataset"),
    ("Congratulations! You are shortlisted for digital marketing internship. Registration fee Rs.1000 via GPay 9123456789.", 1, "internship_fee", "dataset"),
    ("Earn Rs.500 per hour from home. Pay Rs.999 registration to join our team. WhatsApp 9123456789 immediately.", 1, "internship_fee", "dataset"),
    ("Part time job offer. Earn Rs.800 per day. Pay Rs.1500 joining fee first. Send to Paytm 8899001122. Act now.", 1, "parttime_job", "dataset"),
    ("Work from home data entry job. Earn Rs.25000/month. Pay Rs.2000 kit charges to receive your work kit. Pay today only.", 1, "parttime_job", "dataset"),
    ("Like YouTube videos and earn Rs.500 per day. Pay Rs.999 registration fee to join our platform. Limited slots.", 1, "parttime_job", "dataset"),
    ("Earn money by reviewing products online. Pay Rs.1499 activation fee. Earn Rs.1000 per day guaranteed.", 1, "parttime_job", "dataset"),
    ("You have WON Rs.25 lakh in KBC Lucky Draw! Your mobile number was selected. Pay Rs.1500 processing fee to claim prize.", 1, "lottery_prize", "dataset"),
    ("Congratulations! You won Rs.50000 in lucky draw. Share your OTP and pay Rs.500 stamp duty to claim reward.", 1, "lottery_prize", "dataset"),
    ("KBC winner announcement. Your number selected for Rs.10 lakh prize. Pay Rs.2000 clearance fee to agent@gmail.com.", 1, "lottery_prize", "dataset"),
    ("You are selected as lucky winner. Claim Rs.5 lakh prize by paying Rs.999 processing charge. Call 9876543210 now.", 1, "lottery_prize", "dataset"),
    ("Amazon lucky draw winner! You won iPhone 15. Pay Rs.299 delivery charge to 8765432109 via Paytm to receive.", 1, "lottery_prize", "dataset"),
    ("NSP Scholarship of Rs.25000 approved for you. Pay Rs.500 processing fee to PhonePe 8765432109. Credited in 2 hours.", 1, "scholarship_fee", "dataset"),
    ("PM Scholarship Rs.50000 approved. Pay Rs.1000 release fee to receive amount in your bank account. Act immediately.", 1, "scholarship_fee", "dataset"),
    ("Government scholarship of Rs.30000 approved. Pay Rs.800 verification fee to process your application. Limited time.", 1, "scholarship_fee", "dataset"),
    ("UGC scholarship Rs.20000 sanctioned. Pay Rs.600 processing fee to govt.scholarship@gmail.com to release funds.", 1, "scholarship_fee", "dataset"),
    ("Scholarship amount blocked. Pay Rs.299 to unblock and receive Rs.15000 scholarship directly to your account.", 1, "scholarship_fee", "dataset"),
    ("SBI account will be blocked. Verify your KYC immediately by sharing OTP sent to your number. Call 9988001122 urgently.", 1, "otp_fraud", "dataset"),
    ("Your HDFC bank account is suspended. Share OTP to reactivate. Call our helpline 9876543210 immediately.", 1, "otp_fraud", "dataset"),
    ("Dear customer your Paytm KYC is expired. Share OTP received on your number to complete verification. Urgent.", 1, "otp_fraud", "dataset"),
    ("Bank account deactivation alert. To prevent blocking share the OTP sent to your registered mobile. Act now.", 1, "otp_fraud", "dataset"),
    ("Your UPI is blocked. Share OTP with our agent to unblock immediately. Send OTP to 9123456789 on WhatsApp.", 1, "otp_fraud", "dataset"),
    ("ICICI bank security alert. Your account shows suspicious activity. Share OTP to verify identity. Call now.", 1, "otp_fraud", "dataset"),
    ("PhonePe account verification required. Send OTP received on your phone to complete KYC. Urgent action needed.", 1, "otp_fraud", "dataset"),
    ("Axis bank: Your account will be suspended in 2 hours. Share OTP with our executive to prevent suspension.", 1, "otp_fraud", "dataset"),
    ("Fake job offer from TCS. Pay Rs.5000 training fee before joining. Send to tcs.hr@gmail.com immediately.", 1, "job_fee", "dataset"),
    ("Selected for Infosys job. Pay Rs.3000 background verification fee to confirm your appointment letter.", 1, "job_fee", "dataset"),
    ("Job offer from MNC company. Pay Rs.2500 joining fee to receive appointment letter. Limited positions available.", 1, "job_fee", "dataset"),
    ("Wipro selected you for software developer role. Pay Rs.1500 documentation charges to confirm your selection.", 1, "job_fee", "dataset"),
    ("Congratulations on your job selection. Pay Rs.4000 security deposit to HR within 24 hours to confirm joining.", 1, "job_fee", "dataset"),
    ("Amazon work from home job. Pay Rs.1999 for work kit and get Rs.30000 salary. Pay now to start immediately.", 1, "job_fee", "dataset"),
    ("SBI bank impersonation. Your account has been frozen due to KYC mismatch. Update KYC at sbi-kyc.xyz immediately.", 1, "bank_impersonation", "dataset"),
    ("HDFC bank alert: Unusual transaction detected. Click bit.ly/hdfc-secure to verify your account now.", 1, "bank_impersonation", "dataset"),
    ("Your Paytm account will be blocked. Complete KYC verification by clicking on the link sent. Do it urgently.", 1, "bank_impersonation", "dataset"),
    ("RBI notice: Your account linked to suspicious transactions. Pay Rs.500 legal fee to clear your name. Urgent.", 1, "bank_impersonation", "dataset"),
    ("Government free laptop scheme approved. Pay Rs.1500 delivery charge to receive laptop. Limited stock available.", 1, "gov_scheme_fraud", "dataset"),
    ("PM Awas Yojana approved for you. Pay Rs.2000 processing fee to get Rs.2.5 lakh subsidy. Act in 24 hours.", 1, "gov_scheme_fraud", "dataset"),
    ("Free gas connection scheme. Pay Rs.500 registration to get free LPG connection under government scheme.", 1, "gov_scheme_fraud", "dataset"),
    ("Ration card update required. Pay Rs.200 processing fee to update your ration card online. Urgent notice.", 1, "gov_scheme_fraud", "dataset"),
    ("Your application for Software Developer Internship at TCS has been received. Interview scheduled for Monday 3PM IST. Join via Microsoft Teams. No fee required.", 0, "safe", "dataset"),
    ("Hi this is Riya from Internshala support. Your application for software intern role at Flipkart has been shortlisted. Login to internshala.com to complete profile. No fees required.", 0, "safe", "dataset"),
    ("TCS NextStep interview scheduled for Thursday 10AM. Venue TCS office Bangalore. Carry college ID and resume. No charges applicable.", 0, "safe", "dataset"),
    ("Your Infosys application is under review. You will receive email at your registered address for next steps. Visit infosys.com for status.", 0, "safe", "dataset"),
    ("Congratulations on clearing Wipro aptitude test. HR interview scheduled next week. Offer letter will be sent to your email. Zero fees involved.", 0, "safe", "dataset"),
    ("Amazon internship application confirmed. Online assessment link sent to your registered email. Check spam folder. No registration fee.", 0, "safe", "dataset"),
    ("NSP scholarship application submitted successfully. Amount will be directly credited to your Aadhaar linked bank account. Check scholarships.gov.in for status.", 0, "safe", "dataset"),
    ("Your PM scholarship is being processed. No fee required at any stage. Track status at scholarships.gov.in using application number.", 0, "safe", "dataset"),
    ("HDFC bank: For security never share your OTP PIN or password with anyone including bank officials. If asked report to 1930.", 0, "safe", "dataset"),
    ("SBI reminder: Your monthly statement is ready. Login to onlinesbi.sbi to view. Never share OTP with anyone.", 0, "safe", "dataset"),
    ("Google Summer of Code 2024 application received. Results will be announced on official website gsoc.google.com. No fees required.", 0, "safe", "dataset"),
    ("Microsoft internship: Your coding assessment is scheduled. Link sent to registered email. Stipend provided. No joining fee.", 0, "safe", "dataset"),
    ("NPTEL course certificate exam scheduled. Fee Rs.1000 payable only on swayam.gov.in. No third party payment accepted.", 0, "safe", "dataset"),
    ("LinkedIn job alert: 5 new jobs matching your profile. Apply directly on company career pages. No application fee.", 0, "safe", "dataset"),
    ("Internshala coding contest prize money Rs.5000 will be credited to your registered bank account within 7 working days.", 0, "safe", "dataset"),
    ("Your Google Meet interview link for Accenture role: meet.google.com/abc-xyz-def. Scheduled for Friday 2PM. No charges.", 0, "safe", "dataset"),
    ("Campus placement drive: Please bring original marksheets ID proof and 4 passport photos. Reporting time 9AM. Free registration.", 0, "safe", "dataset"),
    ("Congratulations on clearing the written test. HR interview scheduled at Cognizant office next Monday. Travel reimbursement provided.", 0, "safe", "dataset"),
    ("Hackathon result: Your team secured 2nd place. Prize money Rs.10000 will be transferred to team lead account within 14 days.", 0, "safe", "dataset"),
    ("AICTE internship portal: Apply for government approved internships at internship.aicte-india.org. All listings are verified and free.", 0, "safe", "dataset"),
    ("Your UGC NET result is available. Check official results at ugcnet.nta.nic.in using your application number and DOB.", 0, "safe", "dataset"),
    ("Salary credited Rs.18500 to your account ending 4521. Available balance Rs.22340. For queries call 1800-11-2211.", 0, "safe", "dataset"),
    ("Your resume has been viewed by 12 recruiters this week on Naukri. Update your profile at naukri.com to improve visibility.", 0, "safe", "dataset"),
    ("Unstop competition registration confirmed. Participate free at unstop.com. Winners receive cash prizes directly from organizers.", 0, "safe", "dataset"),
    ("HackerRank coding challenge: Your submission ranked 145 out of 5000. Certificate will be emailed to your registered address.", 0, "safe", "dataset"),
    ("Axis bank: Auto debit of Rs.1299 processed for your insurance premium. For queries visit axisbank.com or call 1800-419-5959.", 0, "safe", "dataset"),
    ("Your PF withdrawal of Rs.45000 is approved. Amount will be credited within 3-5 working days to your Aadhaar linked account.", 0, "safe", "dataset"),
    ("IRCTC booking confirmed. PNR 1234567890. Train departs 06:30 from New Delhi. No hidden charges. Ticket attached.", 0, "safe", "dataset"),
    ("Aadhaar update appointment booked at your nearest center. Nominal fee Rs.50 payable at center only. Do not pay online.", 0, "safe", "dataset"),
    ("Your JEE Main admit card is available at jeemain.nta.nic.in. Download using application number. No fee required for download.", 0, "safe", "dataset"),
    ("Internshala: Apply for 500+ free internships updated today. All verified companies. Zero registration fee ever.", 0, "safe", "dataset"),
    ("Company ABC is hiring fresher software developers. Apply at careers page. Written test followed by 2 interviews. No fees.", 0, "safe", "dataset"),
    ("Interview reminder: Your slot is confirmed for tomorrow 11AM at Infosys development center. Carry government ID. No charges.", 0, "safe", "dataset"),
    ("Scholarship disbursement: Rs.3500 credited to your account under NSP Post-Matric scheme. Check scholarships.gov.in for details.", 0, "safe", "dataset"),
    ("Paytm: Rs.500 received from Rahul Kumar. Available balance Rs.1250. For any issues contact support at paytm.com only.", 0, "safe", "dataset"),
    ("Your internship completion certificate from Internshala will be emailed within 3 days. No fee for certificate issuance.", 0, "safe", "dataset"),
    ("EPFO: Your UAN is activated. Access PF account at unifiedportal-mem.epfindia.gov.in. No charges for PF balance check.", 0, "safe", "dataset"),
    ("PhonePe: Transaction of Rs.250 to Swiggy successful. Ref no 1234ABC. For disputes contact support at phonepe.com.", 0, "safe", "dataset"),
    ("Congratulations on clearing the Wipro WILP written test. Next round details will be sent to your registered email soon.", 0, "safe", "dataset"),
    ("Google Pay: Rs.1000 sent to Mom successfully. Transaction ID: GPAY123456. Balance deducted from linked SBI account.", 0, "safe", "dataset"),
    ("HCL Technologies: Your technical interview is scheduled for Wednesday. Video call via Microsoft Teams. No relocation fee.", 0, "safe", "dataset"),
    ("Coursera financial aid approved for Machine Learning course by Stanford. Course is now free for you. Start at coursera.org.", 0, "safe", "dataset"),
    ("Your application to IIT Bombay MTech program has been received. Merit list will be published at iitb.ac.in. No processing fee.", 0, "safe", "dataset"),
    ("Selected for TCS iON internship program. Stipend Rs.10000/month. Joining formalities at nextstep.tcs.com. Zero fees.", 0, "safe", "dataset"),
    ("Cognizant GenC hiring: Written test result declared. You are selected for next round. Details at cognizant.com/careers.", 0, "safe", "dataset"),
    ("Your Naukri profile is 85 percent complete. Add your projects to improve recruiter visibility. Free profile at naukri.com.", 0, "safe", "dataset"),
    ("National level hackathon winner. Your prize cheque of Rs.25000 will be couriered to your college address within 10 days.", 0, "safe", "dataset"),
    ("Internshala Training certificate for Python course issued. Download from your dashboard at internshala.com. No fee.", 0, "safe", "dataset"),
    ("Accenture joining date confirmed as 15th March. Report to Pune office at 9AM. Carry original documents. No charges.", 0, "safe", "dataset"),
    ("Your GATE 2024 scorecard is available at gate2024.iisc.ac.in. Download free using enrollment ID and password.", 0, "safe", "dataset"),
    ("Campus recruitment: ABC company visiting next week. Register free at placement portal. Dress code formal. Bring resume.", 0, "safe", "dataset"),
    ("SBI YONO: Your loan EMI of Rs.8500 auto debited successfully. Next due date 5th March. No extra charges applied.", 0, "safe", "dataset"),
    ("LinkedIn: Your connection request accepted by HR Manager at Infosys. Send a message to discuss opportunities.", 0, "safe", "dataset"),
    ("Wipro Turbo hiring: Aptitude test scheduled online. Link sent to email. No fee. Top performers get direct interview.", 0, "safe", "dataset"),
    ("Earn Rs.500 per hour working from home by liking videos and doing tasks. Pay Rs.2000 registration fee first to start.", 1, "parttime_job", "dataset"),
    ("Investment opportunity: Double your money in 30 days. Pay Rs.5000 and receive Rs.10000 guaranteed. Limited spots only.", 1, "unknown_scam", "dataset"),
    ("Congratulations your Aadhaar linked account has Rs.15000 unclaimed. Pay Rs.299 processing fee to claim your money.", 1, "gov_scheme_fraud", "dataset"),
    ("Free recharge offer! Get Rs.199 recharge free. Click bit.ly/freerecharge and enter OTP to verify your number.", 1, "otp_fraud", "dataset"),
    ("Your account shows Rs.50000 cashback pending. Complete KYC by sharing OTP and bank details to receive cashback.", 1, "otp_fraud", "dataset"),
    ("Freelance work available: Earn Rs.1000 per hour. Pay Rs.1500 deposit to get client list and start earning today.", 1, "parttime_job", "dataset"),
    ("NGO volunteer stipend Rs.20000/month approved. Pay Rs.1000 processing fee to receive your first payment. Urgent.", 1, "unknown_scam", "dataset"),
    ("Your PAN card linked to illegal transactions. Pay Rs.2000 fine to RBI agent to clear your name. Call now.", 1, "bank_impersonation", "dataset"),
    ("Jio free 5G upgrade available. Share OTP received on your number to activate free 5G SIM. Act within 2 hours.", 1, "otp_fraud", "dataset"),
    ("Amazon seller account: Rs.50000 held. Pay Rs.1000 GST charge to release your seller payment immediately.", 1, "bank_impersonation", "dataset"),
    ("WhatsApp gold version available. Click bit.ly/wpgold to upgrade. Enter your number and OTP to verify account.", 1, "otp_fraud", "dataset"),
    ("Selected for UN internship program. Pay Rs.5000 processing fee to British Council office. International opportunity.", 1, "internship_fee", "dataset"),
    ("Your credit card has Rs.10000 reward points expiring today. Pay Rs.199 tax to redeem as cash to your account.", 1, "bank_impersonation", "dataset"),
    ("Government job guaranteed. Pay Rs.10000 registration to get peon clerk constable appointment letter. 100 percent assured.", 1, "job_fee", "dataset"),
    ("Film audition selected. Pay Rs.3000 registration to Bollywood casting agency. Earn Rs.50000 per day as actor.", 1, "unknown_scam", "dataset"),
    ("Your electricity connection will be cut tonight. Pay Rs.3500 immediately to 9876543210 to avoid disconnection.", 1, "unknown_scam", "dataset"),
    ("Income tax refund of Rs.9500 approved. Click link to enter bank details and receive refund directly. Urgent.", 1, "gov_scheme_fraud", "dataset"),
    ("Police cyber cell: Your number used in crime. Pay Rs.5000 fine online to avoid arrest. Call officer immediately.", 1, "unknown_scam", "dataset"),
    ("Crypto investment guaranteed returns 10x in 7 days. Pay Rs.10000 to start. Withdraw anytime. 100 percent safe.", 1, "unknown_scam", "dataset"),
    # ── NEW DOMAIN SCAM ROWS ───────────────────────────────────────
    ("Visit http://university-portal-login.xyz/auth to verify your admission and pay fees", 1, "bank_impersonation", "dataset"),
    ("Your SBI KYC expired. Update now at http://sbi-kyc-update.xyz/verify immediately", 1, "bank_impersonation", "dataset"),
    ("HDFC bank account blocked. Login at http://hdfc-secure-login.tk/auth to unblock", 1, "bank_impersonation", "dataset"),
    ("Claim your Amazon prize at amazon-winner-india.xyz. Pay Rs.299 delivery charge", 1, "lottery_prize", "dataset"),
    ("Internshala internship confirmed. Pay fee at internshala-registration.xyz/pay", 1, "internship_fee", "dataset"),
    ("NSP scholarship released. Claim at nsp-scholarship-gov.xyz/claim within 24 hours", 1, "scholarship_fee", "dataset"),
    ("Google job offer. Apply at google-careers-india.xyz/jobs. Pay Rs.500 registration", 1, "job_fee", "dataset"),
    ("Your Paytm KYC at paytm-kyc-update.site/verify. Share OTP to complete process", 1, "otp_fraud", "dataset"),
    ("Flipkart lucky winner. Visit flipkart-lucky-draw.top/claim. Pay Rs.199 processing", 1, "lottery_prize", "dataset"),
    ("IRCTC free ticket. Claim at irctc-free-ticket.xyz/auth. Enter OTP to verify", 1, "otp_fraud", "dataset"),
    ("gooogle.com free recharge enter OTP to claim Rs.199 cashback today only", 1, "otp_fraud", "dataset"),
    ("g00gle.com selected you for internship pay Rs.999 fee to confirm your slot immediately", 1, "internship_fee", "dataset"),
    ("g0ogle.com job offer pay Rs.2000 training fee before joining date expires tonight", 1, "job_fee", "dataset"),
    ("google-jobs-india.xyz apply now pay Rs.1500 registration fee to confirm your selection", 1, "job_fee", "dataset"),
    ("google-india-careers.top job offer pay Rs.3000 documentation fee to HR department gmail", 1, "job_fee", "dataset"),
    ("amaz0n.in lucky draw winner you won iPhone 15 pay Rs.299 delivery charge to claim prize", 1, "lottery_prize", "dataset"),
    ("amazon-winner-india.xyz congratulations you won Rs.25000 pay Rs.999 processing fee today", 1, "lottery_prize", "dataset"),
    ("amazon-india-prize.top claim your reward pay Rs.499 courier charge to 9876543210 paytm", 1, "lottery_prize", "dataset"),
    ("amazoon.com work from home job offer pay Rs.1999 kit charges to start earning Rs.30000", 1, "job_fee", "dataset"),
    ("amazon-jobs-wfh.xyz work from home opportunity pay Rs.1500 registration to confirm slot", 1, "job_fee", "dataset"),
    ("flipkart-winner.xyz you won Rs.10000 voucher pay Rs.199 processing fee to claim reward", 1, "lottery_prize", "dataset"),
    ("flipkart-lucky-draw.top claim iPhone 14 pay Rs.399 shipping charge to 8765432109 phonepe", 1, "lottery_prize", "dataset"),
    ("fl1pkart.com order refund pending pay Rs.99 processing to receive Rs.5000 refund now", 1, "bank_impersonation", "dataset"),
    ("sbi-kyc-update.xyz urgent KYC required login and share OTP with executive to avoid block", 1, "otp_fraud", "dataset"),
    ("sbi-secure-login.tk your account suspended update KYC at link share OTP immediately", 1, "otp_fraud", "dataset"),
    ("onlinesbi-kyc.xyz SBI account blocked complete KYC verification share OTP to unblock", 1, "otp_fraud", "dataset"),
    ("sbi-alert-kyc.site urgent your SBI account will be blocked share OTP to prevent suspension", 1, "otp_fraud", "dataset"),
    ("sbi-net-banking.xyz login to update your KYC details enter OTP sent to your number", 1, "otp_fraud", "dataset"),
    ("hdfc-secure-login.tk account blocked login at link share OTP with executive to unblock", 1, "otp_fraud", "dataset"),
    ("hdfc-kyc-update.xyz HDFC bank KYC expired update immediately share OTP to reactivate", 1, "otp_fraud", "dataset"),
    ("hdfcbank-alert.site your HDFC account shows suspicious activity share OTP to verify now", 1, "otp_fraud", "dataset"),
    ("icici-secure.xyz ICICI bank account blocked complete KYC share OTP with our agent now", 1, "otp_fraud", "dataset"),
    ("axis-bank-kyc.xyz axis bank urgent KYC update required share OTP to prevent blocking", 1, "otp_fraud", "dataset"),
    ("paytm-kyc.site your Paytm wallet blocked complete KYC by sharing OTP with executive", 1, "otp_fraud", "dataset"),
    ("phonepe-kyc-update.xyz PhonePe account blocked complete KYC share OTP immediately urgent", 1, "otp_fraud", "dataset"),
    ("internsha1a.com internship offer selected pay Rs.1500 registration fee to confirm slot", 1, "internship_fee", "dataset"),
    ("internshala-jobs.xyz internship confirmed pay Rs.999 registration fee via Paytm 9876543210", 1, "internship_fee", "dataset"),
    ("internshala-register.top pay Rs.1200 registration to activate internship offer expires today", 1, "internship_fee", "dataset"),
    ("naukri-jobs.xyz job offer selected pay Rs.2000 documentation fee to confirm appointment", 1, "job_fee", "dataset"),
    ("university-portal-login.xyz complete admission formalities pay Rs.5000 fee at portal now", 1, "bank_impersonation", "dataset"),
    ("college-admission-portal.xyz your admission confirmed pay Rs.3000 processing fee urgently", 1, "bank_impersonation", "dataset"),
    ("student-portal-login.xyz login to complete admission pay Rs.2000 registration immediately", 1, "bank_impersonation", "dataset"),
    ("http://sbi-kyc-verify.xyz/login urgent KYC update required enter OTP to prevent suspension", 1, "otp_fraud", "dataset"),
    ("http://scholarships-gov.xyz/claim your NSP scholarship released pay Rs.500 processing fee", 1, "scholarship_fee", "dataset"),
    ("http://amazon-lucky-winner.xyz/claim you won iPhone pay Rs.299 delivery charge to claim", 1, "lottery_prize", "dataset"),
    ("http://hdfc-secure-kyc.tk/verify account blocked share OTP to complete KYC verification", 1, "otp_fraud", "dataset"),
    ("http://kbc-winner-claim.xyz/prize you won Rs.25 lakh KBC pay Rs.1500 processing to claim", 1, "lottery_prize", "dataset"),
    ("nsp-scholarship.xyz NSP scholarship Rs.25000 approved pay Rs.500 processing fee to release", 1, "scholarship_fee", "dataset"),
    ("kbc-winner-2024.xyz you won KBC lucky draw Rs.25 lakh pay Rs.1500 processing to claim prize", 1, "lottery_prize", "dataset"),
    ("jio-free-5g.xyz Jio free 5G upgrade available enter OTP to activate free 5G plan today", 1, "otp_fraud", "dataset"),
    ("airtel-free-data.xyz Airtel free 10GB data offer enter OTP to activate on your number", 1, "otp_fraud", "dataset"),
    ("tcs-offer-letter.xyz TCS selected you pay Rs.2000 documentation fee to get offer letter", 1, "job_fee", "dataset"),
    ("infosys-joining.xyz Infosys job offer pay Rs.2500 training fee before joining date urgent", 1, "job_fee", "dataset"),
    ("wipro-offer-portal.top Wipro selected pay Rs.1500 documentation fee to confirm appointment", 1, "job_fee", "dataset"),
    ("incometax-refund.xyz income tax refund Rs.9500 enter bank details to receive refund now", 1, "gov_scheme_fraud", "dataset"),
    ("facebo0k.com account security alert your account compromised share OTP to recover access", 1, "otp_fraud", "dataset"),
    ("whatsapp-upgrade.xyz WhatsApp gold version upgrade enter OTP and number to activate now", 1, "otp_fraud", "dataset"),
    ("instagram-verify.xyz Instagram account verification required enter OTP to prevent deletion", 1, "otp_fraud", "dataset"),
    ("netflix-free-subscription.xyz Netflix free 1 year subscription enter OTP to activate now", 1, "otp_fraud", "dataset"),
    ("microsoft-office-free.xyz free Microsoft Office for students enter OTP to download now", 1, "otp_fraud", "dataset"),
    # ── SAFE ROWS ─────────────────────────────────────────────────
    ("Your TCS interview is scheduled at nextstep.tcs.com on Monday 10AM. No fee required.", 0, "safe", "dataset"),
    ("Internshala confirmed your internship application. Login at internshala.com to proceed.", 0, "safe", "dataset"),
    ("SBI bank: We will NEVER ask for your OTP. Report fraud at 1930 or visit sbi.co.in", 0, "safe", "dataset"),
    ("NSP scholarship status: Check at scholarships.gov.in using your application number.", 0, "safe", "dataset"),
    ("Your Amazon order has been confirmed. Track at amazon.in. No additional charges.", 0, "safe", "dataset"),
    ("Google Meet interview link sent to your email. Join at meet.google.com. No fees.", 0, "safe", "dataset"),
    ("HDFC bank reminder: Never share OTP. Call 1800-202-6161 for support. Visit hdfcbank.com", 0, "safe", "dataset"),
    ("Your Infosys offer letter sent to registered email. Joining date 15th March. No charges.", 0, "safe", "dataset"),
    ("NPTEL certificate exam fee Rs.1000 payable only at swayam.gov.in. No third party payment.", 0, "safe", "dataset"),
    ("Wipro WILP results declared. Check at wipro.com/careers. Interview scheduled next week.", 0, "safe", "dataset"),
    ("PhonePe transaction of Rs.500 to Swiggy successful. For issues contact phonepe.com only.", 0, "safe", "dataset"),
    ("Your PF withdrawal approved. Amount credited within 3-5 days. Track at epfindia.gov.in", 0, "safe", "dataset"),
    ("LinkedIn job alert: 5 new matches. Apply directly at company career pages. No fees.", 0, "safe", "dataset"),
    ("Cognizant GenC next hiring: Results at cognizant.com/careers. Interview scheduled soon.", 0, "safe", "dataset"),
    ("Accenture joining confirmed for 15th March. Report to Pune office. No charges applicable.", 0, "safe", "dataset"),
    ("GATE 2024 scorecard available at gate2024.iisc.ac.in. Download free using enrollment ID.", 0, "safe", "dataset"),
    ("Your JEE Main admit card at jeemain.nta.nic.in. Download free. No payment required.", 0, "safe", "dataset"),
    ("Unstop competition registration confirmed. Participate free at unstop.com. Prize from organizer.", 0, "safe", "dataset"),
    ("HackerRank certificate emailed to registered address. No fee for certificate issuance.", 0, "safe", "dataset"),
    ("Campus placement: ABC company visiting next week. Register free at placement portal.", 0, "safe", "dataset"),
]

OUTPUT_PATH = "data/scam_dataset.csv"
os.makedirs("data", exist_ok=True)

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(
        f,
        quoting    = csv.QUOTE_ALL,
        quotechar  = '"',
        escapechar = "\\",
    )
    writer.writerow(["text", "label", "category", "source"])
    writer.writerows(ALL_ROWS)

print(f"Written {len(ALL_ROWS)} rows to {OUTPUT_PATH}")
print("Now run: python train/train_model.py")